name: Maven Publish Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get tag name
        run: echo "The tag name is ${{ github.ref | replace('refs/tags/', '') }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn package

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/WindSurf-${{ github.ref | replace('refs/tags/', '') }}-SNAPSHOT.jar"
